config/routes.rb
Rails.application.routes.draw do
  resources :companies do
    resources :claims, only: [:create, :destroy, :edit, :update]
    end
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
    devise_for :users
    root 'companies#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/claim.rb
class Claim < ApplicationRecord
  belongs_to :user
  belongs_to :company
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :claims, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :claims, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/claims_controller.rb
class ClaimsController < ApplicationController
  def create
    @company = Company.find(params[:company_id])
    @claim = Claim.new(content:params[:claim][:content], user: current_user)
    @claim.company = @company
    @claim.save
  end
end

app/controllers/companies_controller.rb
class CompaniesController < InheritedResources::Base
  before_action :authenticate_user!, except: [:index]
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  def index
    @companies = Company.all
    @company = Company.new
  end

  def create
    @company = Company.create(company_params)
    respond_to do |format|
    format.js
    end
  end

  def show
    @claims = Claim.all.order('created_at DESC')
   end

  def destroy
    @company.destroy
    respond_to do |format|
    format.js
    end
  end

  def edit
  end


  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
        format.js {}

      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  private

  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/claims/_claim.html.erb
<li><%= @claim.content %></li>

app/views/claims/create.js.erb
$('#claims').append("<%= j render 'claim' %>");
$('#texto').val('');

app/views/companies/_companies.html.erb
<tr>
<td><%= @company.name %></td>
<td><%= link_to 'Show', @company %></td>
<td><%= link_to 'Edit', edit_company_path(@company), data: {remote: true} %></td>
<td><%= link_to 'Destroy', @company, method: :delete, data: { confirm: 'Are you sure?', remote: true } %></td>
</tr>

app/views/companies/_form.html.erb
<%= form_with(model: @company) do |form| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/_modal_edit.html.erb
<%= form_with(model: @company) do |form| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/create.js.erb
$("#companies").append("<%= j render 'companies' %>");

app/views/companies/destroy.js.erb
$('#<%=@company.id%>').toggle(1000);

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/edit.js.erb
$('#modal_id').html("<%= j render 'modal_edit' %>")
$('#exampleModal').modal('show')

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<%= form_with(model: @company) do |form| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id = "companies">
    <% @companies.each do |company| %>
      <tr id = "<%= company.id%>">
        <td id = "company_<%= company.id%>" ><%= company.name %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company), data: {remote: true} %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<!-- Button trigger modal -->
<!-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Launch demo modal
</button> -->

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        </button>
      </div>
      <div class="modal-body" id = "modal_id" >

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<%= form_with(model: [@company, Claim.new]) do |f| %>
<%= f.text_area :content, placeholder: 'Escribe tu comentario aquí...', id: :text %>
<%= f.submit 'Comentar' %>
<% end %>

<div id="claims">
  <ol >
    <%@claims.each do |claim| %>
    <% if (@company.id == claim.company_id) %>
      <li><%= claim.content %></li>
      <% end %>
    <% end %>
  </ol>

</div>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/companies/update.js.erb
$('#exampleModal').modal('hide');
$('#company_<%=@company.id%>').html('<%= @company.name %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MonitoreoReclamos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">AJAX</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Inicio <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if user_signed_in? %>
          <%= current_user.email %>
          <% else %>
          Ingreso
          <% end %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <% if user_signed_in? %>
          <a class="dropdown-item" href="<%= destroy_user_session_path %>" data-method="DELETE">Salir</a>
          <% else %>
          <a class="dropdown-item" href="<%= new_user_session_path %>">Ingreso</a>
          <a class="dropdown-item" href="<%= new_user_registration_path %>">Registro</a>
          <% end %>
          </div>
      </li>
    </ul>
  </div>
</nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <div class = "container" >
      <%= yield %>
    </div>
    
  </body>
</html>